#!/usr/bin/env python3

import argparse
import json
import shutil
import socket
import sys
import pathlib
import platform

from dataclasses import dataclass

if sys.version_info < (3, 9):
    print('Python version >= 3.9 is required!')
    exit(1)

DOTPKG_MANIFEST_NAME = 'dotpkg.json'
IGNORED_NAMES = {DOTPKG_MANIFEST_NAME, '.git', '.DS_Store'}

# Helpers

RED_COLOR = '\033[91m'
YELLOW_COLOR = '\033[93m'
BLUE_COLOR = '\033[36m'
GRAY_COLOR = '\033[90m'
GREEN_COLOR = '\033[92m'
PINK_COLOR = '\033[95m'
CLEAR_COLOR = '\033[0m'

@dataclass
class Options:
    dry_run: bool
    assume_yes: bool

def message(color: str, msg: str):
    print(f'{color}==> {msg}{CLEAR_COLOR}')

def error(msg: str):
    message(RED_COLOR, msg)
    exit(1)

def warn(msg: str):
    message(YELLOW_COLOR, msg)

def info(msg: str):
    message(BLUE_COLOR, msg)

def success(msg: str):
    message(GREEN_COLOR, msg)

def note(msg: str):
    print(f'{GRAY_COLOR}{msg}{CLEAR_COLOR}')

def prompt(msg: str, choices: list[str], default: str, opts: Options):
    if opts.assume_yes:
        return default

    aliases = {}
    option_strs = []

    if choices:
        for choice in choices:
            i = 1
            while choice[:i] in aliases.keys():
                i += 1
            aliases[choice[:i]] = choice
            option_strs.append(f'[{choice[:i]}]{choice[i:]}')

    choices_str = f" - {', '.join(option_strs)}"
    response = input(f"{PINK_COLOR}==> {msg}{choices_str} {CLEAR_COLOR}")

    return aliases.get(response, response)

def confirm(msg: str, opts: Options):
    response = prompt(msg, ['yes', 'no'], 'yes', opts)
    return response == 'yes'

# Manifest resolution

MANIFEST_VARS = {
    '${home}': str(pathlib.Path.home().resolve()),
    '${hostname}': socket.gethostname()
}

def resolve_manifest_str(s: str) -> str:
    resolved = s
    for key, value in MANIFEST_VARS.items():
        resolved = resolved.replace(key, value)
    return resolved

def find_target_dir(manifest: dict) -> pathlib.Path:
    raw_dirs = manifest.get('targetDir', ['${home}'])

    for raw_dir in raw_dirs:
        path = pathlib.Path(resolve_manifest_str(raw_dir))
        if path.is_dir() and path.exists():
            return path

    error(f'No suitable targetDir found in {raw_dirs}!')

def unsatisfied_path_requirements(manifest: dict) -> list[str]:
    for requirement in manifest.get('requiresOnPath', []):
        if not shutil.which(requirement):
            yield requirement

def manifest_name(path: pathlib.Path, manifest: dict) -> str:
    return manifest.get('name', path.name)

# Installation/uninstallation

def find_link_candidates(src_dir: pathlib.Path, target_dir: pathlib.Path, renamer = lambda n: n):
    for src_path in src_dir.iterdir():
        name = renamer(src_path.name)
        target_path = target_dir / name

        if name not in IGNORED_NAMES:
            # We only descend into existing directories that are not Git repos
            if target_path.exists() and not target_path.is_symlink() and target_path.is_dir() and not (target_path / '.git').exists():
                yield from find_link_candidates(src_path, target_path)
            else:
                yield src_path, target_path

def copy(src_path: pathlib.Path, target_path: pathlib.Path, opts: Options):
    print(f'Copying {src_path} to {target_path}')
    if not opts.dry_run:
        shutil.copy(src_path, target_path)

def move(src_path: pathlib.Path, target_path: pathlib.Path, opts: Options):
    print(f'Moving {src_path} to {target_path}')
    if not opts.dry_run:
        shutil.move(src_path, target_path)

def add_link(src_path: pathlib.Path, target_path: pathlib.Path, opts: Options):
    print(f'Linking {target_path} -> {src_path}')
    if not opts.dry_run:
        target_path.symlink_to(src_path)

def remove(target_path: pathlib.Path, opts: Options):
    print(f'Removing {target_path}')
    if not opts.dry_run:
        target_path.unlink()

def install(src_dir: pathlib.Path, manifest: dict, opts: Options):
    target_dir = find_target_dir(manifest)
    host_specific_patterns = manifest.get('hostSpecificFiles', [])
    host_specific_includes = {
        src_dir / resolve_manifest_str(p)
        for p in host_specific_patterns
    }
    host_specific_ignores = {
        i
        for p in host_specific_patterns
        for i in src_dir.glob(p.replace('${hostname}', '*'))
        if i not in host_specific_includes and not i.name.endswith('.private')
    }
    custom_ignores = {
        i
        for p in manifest.get('ignoredFiles', [])
        for i in src_dir.glob(p)
    }
    ignores = host_specific_ignores.union(custom_ignores)
    renames = manifest.get('renames', {})
    
    def renamer(name):
        for pat, s in renames.items():
            name = name.replace(resolve_manifest_str(pat), resolve_manifest_str(s))
        return name

    for src_path, target_path in find_link_candidates(src_dir, target_dir, renamer):
        if src_path in ignores:
            note(f'Ignoring {src_path}')
        elif target_path.exists():
            if not target_path.is_symlink() or target_path.resolve() != src_path.resolve():
                def backup():
                    move(target_path, target_path.with_name(f'{target_path.name}.backup'), opts)
                    add_link(src_path, target_path, opts)

                def overwrite():
                    remove(target_path, opts)
                    add_link(src_path, target_path, opts)

                def skip():
                    note(f'Skipping {target_path}')

                choices = {
                    'backup': backup,
                    'overwrite': overwrite,
                    'skip': skip
                }

                response = prompt(f'{target_path} exists and is not a link into the dotpkg.', sorted(choices.keys()), 'skip', opts)
                choices.get(response, skip)()
            else:
                note(f'Skipping {target_path} (already linked)')
        else:
            add_link(src_path, target_path, opts)

def uninstall(src_dir: pathlib.Path, manifest: dict, dry_run: bool):
    target_dir = find_target_dir(manifest)
    for src_path, target_path in find_link_candidates(src_dir, target_dir):
        if target_path.is_symlink() and target_path.resolve() == src_path.resolve():
            remove(target_path, dry_run)
        else:
            print(f'Skipping {target_path} (not a link into the dotpkg)')

# Dotpkg resolution

def cwd_dotpkgs() -> list[str]:
    return [
        p.name
        for p in pathlib.Path.cwd().iterdir()
        if not p.name in IGNORED_NAMES and (p / DOTPKG_MANIFEST_NAME).exists()
    ]

def resolve_dotpkgs(dotpkgs: list[str]) -> list[pathlib.Path]:
    for dotpkg in dotpkgs:
        path = pathlib.Path.cwd() / dotpkg
        manifest_path = path / DOTPKG_MANIFEST_NAME

        if not path.exists() or not path.is_dir():
            error(f"Dotpkg '{dotpkg}' does not exist in cwd!")
        if not manifest_path.exists():
            error(f"Missing dotpkg.json for '{dotpkg}'!")

        with open(str(manifest_path), 'r') as f:
            manifest = json.loads(f.read())

        yield path, manifest

# CLI

def install_cmd(dotpkgs: list[str], opts: Options):
    check_path = False
    check_platforms = False

    if not dotpkgs:
        dotpkgs = cwd_dotpkgs()
        check_path = True
        check_platforms = True
        if not confirm(f"Install dotpkgs {', '.join(dotpkgs)}?", opts):
            print('Cancelling')
            exit(0)

    for path, manifest in resolve_dotpkgs(dotpkgs):
        name = manifest_name(path, manifest)
        description = manifest.get('description', '')
        unsatisfied_reqs = list(unsatisfied_path_requirements(manifest))
        supported_platforms = set(manifest.get('platforms', []))
        our_platform = platform.system().lower()

        if not check_platforms or not supported_platforms or (our_platform in supported_platforms):
            if not check_path or not unsatisfied_reqs:
                info(f'Installing {name} ({description})...')
                install(path, manifest, opts)
            else:
                warn(f"Skipping {name} (could not find {', '.join(unsatisfied_reqs)} on PATH)")
        else:
            warn(f"Skipping {name} (platform {our_platform} is not supported, supported are {', '.join(sorted(supported_platforms))})")

def uninstall_cmd(dotpkgs: list[str], opts: Options):
    if not dotpkgs:
        dotpkgs = cwd_dotpkgs()
        if not confirm(f"Uninstall dotpkgs {', '.join(dotpkgs)}?", opts):
            print('Cancelling')
            exit(0)

    for path, manifest in resolve_dotpkgs(dotpkgs):
        info(f"Uninstalling {manifest_name(path, manifest)} ({manifest.get('description', '')})...")
        uninstall(path, manifest, opts)

COMMANDS = {
    'install': install_cmd,
    'uninstall': uninstall_cmd
}

def main():
    parser = argparse.ArgumentParser(description='Dotfile package manager')
    parser.add_argument('-d', '--dry-run', action='store_true', help='Simulate a run without any modifications to the file system.')
    parser.add_argument('-y', '--assume-yes', action='store_true', help='Accept prompts with yes and run non-interactively (great for scripts)')
    parser.add_argument('command', choices=sorted(COMMANDS.keys()), help='The command to invoke')
    parser.add_argument('dotpkgs', nargs=argparse.ZERO_OR_MORE, help='The dotpkgs to install (all by default)')

    args = parser.parse_args()
    opts = Options(dry_run=args.dry_run, assume_yes=args.assume_yes)

    if opts.dry_run:
        warn("Performing dry run (i.e. not actually changing any files)")

    COMMANDS[args.command](args.dotpkgs, opts)

if __name__ == '__main__':
    main()
