from pathlib import Path

DOTPKG_MANIFEST_NAME = 'dotpkg.json'
DOTPKG_STATE_DIR = Path.home() / '.local' / 'state' / 'dotpkg'
INSTALL_MANIFEST_NAME = 'installs.json'
INSTALL_MANIFEST_PATH = DOTPKG_STATE_DIR / INSTALL_MANIFEST_NAME
INSTALL_MANIFEST_VERSION = 2
IGNORED_NAMES = {DOTPKG_MANIFEST_NAME, INSTALL_MANIFEST_NAME, '.git', '.gitignore', '.DS_Store'}
