name: Check

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip3 install .
    - name: Install Pyright
      run: npm install -g pyright
    - name: Run code generation
      run: scripts/generate-models
    - name: Check that the generated files match the repo
      run: |
        diff=`git diff HEAD`
        echo "$diff"
        test -z "$diff"
    - name: Typecheck
      run: pyright
    - name: Run tests
      run: python3 -m unittest
